version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 8080:80
      - 443:443
  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
      