<x-layout>
    <main style="  box-sizing: border-box;width:100% ;padding:20px;height:100%;">
        <div id="card" style=" box-sizing: border-box;margin:0;padding:25px;height:100%">
            <h2>Par Mums</h2>
            <div class="body" style="color:gray;font-size:16px">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam quam nulla porttitor massa id neque aliquam. Consequat id porta nibh venenatis. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Eu nisl nunc mi ipsum faucibus. Id aliquet risus feugiat in. Morbi enim nunc faucibus a pellentesque sit. Aliquet bibendum enim facilisis gravida neque convallis. Pharetra magna ac placerat vestibulum lectus. In hendrerit gravida rutrum quisque.</p>
                <p>Id ornare arcu odio ut sem nulla. Sem viverra aliquet eget sit amet tellus cras adipiscing. Ullamcorper morbi tincidunt ornare massa eget. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Sem viverra aliquet eget sit amet. Egestas integer eget aliquet nibh. Non blandit massa enim nec dui nunc. Rhoncus urna neque viverra justo nec. Neque laoreet suspendisse interdum consectetur. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Egestas purus viverra accumsan in nisl. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Urna nunc id cursus metus aliquam eleifend mi. Tincidunt lobortis feugiat vivamus at augue. Convallis posuere morbi leo urna molestie at elementum eu. Euismod elementum nisi quis eleifend. Augue mauris augue neque gravida. Justo eget magna fermentum iaculis eu non diam phasellus. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur.</p>
                <p>Risus quis varius quam quisque id diam vel quam. Et malesuada fames ac turpis egestas integer eget aliquet. Volutpat ac tincidunt vitae semper quis lectus nulla. Nunc faucibus a pellentesque sit amet. Suspendisse sed nisi lacus sed viverra tellus. Pharetra et ultrices neque ornare. Duis ultricies lacus sed turpis tincidunt. Sit amet luctus venenatis lectus magna fringilla. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Aliquam purus sit amet luctus venenatis.</p>
                <p>Senectus et netus et malesuada. Dui nunc mattis enim ut tellus elementum sagittis vitae. Eget nullam non nisi est sit amet. Non sodales neque sodales ut. Sagittis eu volutpat odio facilisis mauris sit amet massa. Ullamcorper sit amet risus nullam. Turpis egestas pretium aenean pharetra magna. Nec ullamcorper sit amet risus nullam. Lacus sed turpis tincidunt id aliquet. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Mauris rhoncus aenean vel elit. Neque egestas congue quisque egestas diam in arcu cursus euismod. Justo laoreet sit amet cursus. Scelerisque eu ultrices vitae auctor eu. Lorem mollis aliquam ut porttitor leo a. Vitae congue mauris rhoncus aenean vel. In hac habitasse platea dictumst. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare.</p>
                <p>Tristique risus nec feugiat in. Morbi tristique senectus et netus. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Augue eget arcu dictum varius duis at consectetur lorem donec. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Euismod quis viverra nibh cras pulvinar mattis nunc sed. Accumsan tortor posuere ac ut consequat semper viverra nam. Tellus at urna condimentum mattis pellentesque id. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Ac turpis egestas integer eget aliquet nibh. Cras sed felis eget velit aliquet sagittis id. Cras ornare arcu dui vivamus arcu felis. Sed arcu non odio euismod lacinia at quis risus sed. A iaculis at erat pellentesque adipiscing commodo elit. Neque vitae tempus quam pellentesque nec nam aliquam sem. Mauris pellentesque pulvinar pellentesque habitant morbi tristique.</p>
                <p>Eget magna fermentum iaculis eu non. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Enim nunc faucibus a pellentesque sit amet. Suspendisse ultrices gravida dictum fusce ut placerat orci. Tortor at auctor urna nunc id cursus metus aliquam eleifend. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Tortor posuere ac ut consequat semper viverra nam libero justo. Eu sem integer vitae justo eget magna fermentum iaculis eu. Orci dapibus ultrices in iaculis nunc sed. Ante metus dictum at tempor commodo ullamcorper a. Mattis vulputate enim nulla aliquet. Cursus metus aliquam eleifend mi in.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Sed adipiscing diam donec adipiscing tristique. Imperdiet nulla malesuada pellentesque elit. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Est sit amet facilisis magna etiam tempor. Arcu non odio euismod lacinia at quis risus sed. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Adipiscing diam donec adipiscing tristique risus nec feugiat. Nunc aliquet bibendum enim facilisis gravida. Sed velit dignissim sodales ut eu sem integer. Magna etiam tempor orci eu lobortis elementum nibh.</p>
                <p>Quis imperdiet massa tincidunt nunc pulvinar sapien et. Fusce ut placerat orci nulla pellentesque dignissim enim. Proin nibh nisl condimentum id venenatis. Sed id semper risus in hendrerit gravida. Porttitor eget dolor morbi non arcu risus quis varius quam. Enim diam vulputate ut pharetra sit amet aliquam id. Mattis pellentesque id nibh tortor id. In dictum non consectetur a erat nam. Suscipit adipiscing bibendum est ultricies integer. Urna et pharetra pharetra massa massa ultricies. Blandit volutpat maecenas volutpat blandit. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Non odio euismod lacinia at quis risus sed vulputate. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Aliquet porttitor lacus luctus accumsan. Nunc eget lorem dolor sed viverra ipsum nunc. Purus in mollis nunc sed.</p>
                <a id="default_button" style="width: fit-content;margin-top:10px;" href="/" >Atpakaļ</a>
            </div>
        </div>
    </main>
</x-layout>